name: Dcoker Image CI

on:
  push: 
  branches: [main]
  pull_request: [main]

  jobs:

  build: 
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3.5.2
  - name: Build the Dcoker Image
    run: docker build . --file Dockerfile --tag my-image-name:$(data +%s)
