name: Test
on:
 push:
    branches: [master]
 pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Lint Action
        uses: wearerequired/lint-action@v2.3.0
